# Generated by Django 5.0 on 2025-04-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
